### ISSUE TITLE
Einfluss auf die Labels und input-group Container

### ISSUE THREAD

**Issue by ways2web** [netzmacht/contao-bootstrap#70]
es wäre toll, wenn man  für die Labels und Input-group Container klassen vergeben könnte.
Wofür?  Um validation states nutzen zu können:

http://getbootstrap.com/css/#forms-control-validation

Jedoch sehe ich ein, dass es eventuell zu aufwändig ist um die kleine Option über den Fg nutzen zu können. Jedoch wollte ich das feature-request mal erwecken.

**Comment by dmolineus** [comment]
Da Contao nur Fehlermeldungen kennt, unterstütze ich dies erst einmal nicht. Ggf. etwas für eine separate Erweiterung "Erweiterte Formularvalidierung" oder ähnlich.
